[package]
name = "tb64"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
cfg-if = "1.0.1"
clap = { version = "4.5.40", features = ["derive"] }
cli-clipboard = "0.4.0"
nix = "0.30.1"

[dependencies.windows-sys]
version = "0.60"
features = [
    "Win32_System_Console",
]
